---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pipeline info
        run: echo "Launched from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: Run a multi-line script
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "The job context ${JOB_CONTEXT}"
